package bg.softuni.Jukebox.genre;

public enum GenreType {
    COUNTRY, HIP_HOP, ROCK, EARLY_MUSIC, FOLK_MUSIC, REGGAE, ELECTRONIC, JAZZ, SOUL_MUSIC,
    BLUES_ROCK, COMPUTER_MUSIC, POP, BLUES, DISCO, METAL, R_AND_B,
    CLASSIC, GRUNGE, DRUM_AND_BASS
}
