package bg.softuni.Jukebox.model.entity.enums;

public enum GenreType {
    COUNTRY, HIP_HOP, ROCK, EARLY_MUSIC, FOLK_MUSIC, REGGAE, ELECTRONIC, JAZZ, SOUL_MUSIC,
    BLUES_ROCK, MUSIC_OF_LATIN_AMERICA, COMPUTER_MUSIC, FINK, POP, BLUES, DISCO, METAL, R_AND_B,
    CLASSIC, GRUNGE, DRUM_AND_BASS
}
